In [1]:
#to install torch library
!pip3 install torch torchvision

In [2]:
from torch import torch

In [3]:
#setting the seed to get same output
torch.manual_seed(42)

#intializing a random tensor
matrix=torch.rand(4,3)

In [4]:
#to chech if it tensor or not
print(torch.is_tensor(matrix))

True


In [5]:
print(matrix)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


Tensors are mutlidimensional arrays

In [6]:
print(matrix.shape)

torch.Size([4, 3])


In [13]:
#element wise angle of the given input tensor
torch.angle(matrix)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
#returns the indice of the maximum value in the tensor
print('Argmax-',torch.argmax(matrix),'\n')

#return the maximum value  in the tensor
print('max value-',torch.max(matrix))

Argmax- tensor(3) 

max value- tensor(0.9593)


In [18]:
torch.max(matrix)

tensor(0.9593)

In [7]:
#matrix transpose

torch.t(matrix)

tensor([[0.8823, 0.9593, 0.2566, 0.1332],
        [0.9150, 0.3904, 0.7936, 0.9346],
        [0.3829, 0.6009, 0.9408, 0.5936]])

In [8]:
#reshaping the tensor

new_matrix=matrix.reshape(6,2)

print(new_matrix)

new_matrix.shape

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009],
        [0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])


torch.Size([6, 2])

Operations between two tensors

In [9]:
torch.manual_seed(42)

tensor_1=torch.randn(2,2)
tensor_2=torch.randn(2,2)

In [10]:
#addition

print(torch.add(tensor_1,tensor_2), '\n')


#Subtraction

print(torch.sub(tensor_1,tensor_2), '\n')

#Division

print(torch.div(tensor_1,tensor_2),'\n')

#multiplication

print(torch.mm(tensor_1,tensor_2))

tensor([[-0.7862, -0.0575],
        [ 2.4427, -0.4077]]) 

tensor([[ 1.4595,  0.3151],
        [-1.9737,  0.8683]]) 

tensor([[-0.2999, -0.6913],
        [ 0.1062, -0.3610]]) 

tensor([[-0.0936, -0.1449],
        [ 0.2454, -0.1906]])


In [11]:
print('tensor 1',tensor_1,'\n')

print('tensor 2',tensor_2,'\n')

#Concatenating two tensors vertically

print('vertically added tensors',torch.cat((tensor_1,tensor_2)),'\n')

#Concatenating two tensors horizontally
 
print('horizontally added tensors',torch.cat((tensor_1,tensor_2),dim=1))

tensor 1 tensor([[0.3367, 0.1288],
        [0.2345, 0.2303]]) 

tensor 2 tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380]]) 

vertically added tensors tensor([[ 0.3367,  0.1288],
        [ 0.2345,  0.2303],
        [-1.1229, -0.1863],
        [ 2.2082, -0.6380]]) 

horizontally added tensors tensor([[ 0.3367,  0.1288, -1.1229, -0.1863],
        [ 0.2345,  0.2303,  2.2082, -0.6380]])


In [22]:
#returns element wise maximum value of the two input tensors
torch.maximum(tensor_1,tensor_2)

tensor([[0.3367, 0.1288],
        [2.2082, 0.2303]])